### ISSUE TITLE
Go template expose more port numbers 

### ISSUE THREAD

**Issue by mgijsberti** [wouterd/hippo-docker#2]
tomcat_port=$(docker inspect --format '{{ range .NetworkSettings.Ports }}{{ range . }}{{ .HostPort }}{{end}}{{end}}' ${container_id})

If we want to expose for instance the rmi port 1099.

Thanks,
Martijn

**Comment by wouterd** [comment]
Clarification: start-integration-server.sh breaks when more than one port is being exposed by the SUT.
