### ISSUE TITLE
Script "run-integration-test.sh" fails

### ISSUE THREAD

**Issue by hbokh** [wouterd/hippo-docker#4]
Hi Wouter,

The run-integration-test.sh -script fails with a Docker-error "no Dockerfile found" :

```
[...]
Removing intermediate container 0eb47ea6e96b
Successfully built 7d59c22492fc
2014/08/13 12:24:32 no Dockerfile found in .

Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
[...]
```

Both when run from directory "myhippoproject/run-integration-test.sh" inside the Vagrant-machine, also directly in "myhippoproject" as ./run-integration-test.sh.
Must be the command in line 2

```
docker build --rm -q=false .
```

since the only "Dockerfiles" are to be found in other / deeper subdirectories, e.g docker-images/*/*.
I'm not using boot2docker on Ubuntu, but use your Vagrantfile and only changed config.vm.box "saucy64" into "trusty64".

A list of containers (none) and images in the VM:

```
root@vagrant-ubuntu-trusty-64:/vagrant# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

root@vagrant-ubuntu-trusty-64:/vagrant# docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
wouterd/tomcat        latest              7d59c22492fc        7 minutes ago       642.5 MB
wouterd/oracle-jre7   latest              916e274538eb        8 minutes ago       634.4 MB
```

Any insights welcome!

Groet, Henk

**Comment by wouterd** [comment]
Hi Henk!

That's an old first try script, I should've removed it.
The actual "magic" happens in the files under the myhippoproject/integrationtests/src/test/script folder.
There's a start-integration-server.sh and stop-integration-server.sh in there that do the pre- and post- integrationtest phases.

If you do a mvn clean verify in the myhippoproject folder, they get used.

Hope that helps!

**Comment by hbokh** [comment]
Cheers Wouter!  
So the script is obsolete. I won't be using it then - and close the issue.  
Dank, Henk
